runtime: nodejs18

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

instance_class: F1

# 성능 및 스케일링 설정
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# 헬스 체크 설정
liveness_check:
  path: "/api/status"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# 정적 파일 핸들러 및 라우팅
handlers:
- url: /.*
  script: auto
  secure: always

env: flex 