name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # 또는 master 등 메인 브랜치명

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd backend && npm install

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Display gcloud info
      run: |
        gcloud info
        gcloud config list

    - name: Create App Engine app if not exists
      run: |
        gcloud app describe --project=${{ env.PROJECT_ID }} || gcloud app create --region=asia-northeast3 --project=${{ env.PROJECT_ID }}
      continue-on-error: true

    - name: Deploy to App Engine
      id: deploy
      run: |
        cd backend
        ls -la
        cat app.yaml
        echo "y" | gcloud app deploy --no-promote --verbosity=debug --project=${{ env.PROJECT_ID }} 