name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # 또는 master 등 메인 브랜치명

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: shipping

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd backend && npm install

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Set project ID
      run: gcloud config set project ${{ env.PROJECT_ID }}

    - name: Verify gcloud configuration
      run: |
        gcloud --version
        gcloud config list
        gcloud auth list

    - name: Create app.yaml configuration
      run: |
        cd backend
        ls -la
        cat app.yaml
        echo "Creating backup of app.yaml"
        cp app.yaml app.yaml.bak
        
        echo "Updating app.yaml for deployment"
        cat > app.yaml << EOF
        runtime: nodejs18
        service: backend-api
        env_variables:
          PORT: 8080
        entrypoint: node server.js
        handlers:
        - url: /.*
          script: auto
        EOF
        
        echo "Updated app.yaml content:"
        cat app.yaml

    - name: Deploy to App Engine
      id: deploy
      run: |
        cd backend
        echo "Running gcloud app deploy"
        echo "y" | gcloud app deploy --quiet 