name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # 또는 master 등 메인 브랜치명

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        working_directory: ./  # 배포할 디렉토리 (backend만 배포하려면 ./backend)
        version: v${{ github.run_number }} # 버전을 GitHub Actions 실행 번호로 설정 