name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # 또는 master 등 메인 브랜치명

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: fresh-edge-451807-h7  # 실제 GCP 프로젝트 ID

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd backend && npm install

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        create_credentials_file: true

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Set project ID
      run: gcloud config set project ${{ env.PROJECT_ID }}

    - name: Verify gcloud configuration
      run: |
        gcloud --version
        gcloud config list
        gcloud auth list

    # 참고: 다음 작업을 Google Cloud Console에서 수동으로 완료해야 합니다:
    # 1. 필요한 API 활성화:
    #    - App Engine API (appengine.googleapis.com)
    #    - Cloud Build API (cloudbuild.googleapis.com)
    #    - Cloud Resource Manager API (cloudresourcemanager.googleapis.com)
    # 2. App Engine 애플리케이션 생성:
    #    - App Engine 메뉴에서 "앱 만들기" 선택
    #    - 리전으로 "asia-northeast3" (서울) 선택
    #    - 안내에 따라 진행

    - name: Create app.yaml configuration
      run: |
        cd backend
        ls -la
        echo "Creating app.yaml for deployment"
        cat > app.yaml << EOF
        runtime: nodejs18
        service: backend-api
        env_variables:
          PORT: 8080
        entrypoint: node server.js
        
        # Automatic scaling configuration
        automatic_scaling:
          max_instances: 5  # Maximum number of instances
          min_instances: 0  # Minimum number of instances
          
        handlers:
        - url: /.*
          script: auto
        EOF
        
        echo "app.yaml content:"
        cat app.yaml

    - name: Deploy to App Engine
      id: deploy
      run: |
        cd backend
        echo "Running gcloud app deploy"
        gcloud app deploy --quiet --project=${{ env.PROJECT_ID }} --verbosity=debug 